<a href="https://colab.research.google.com/github/PrajuMaharjan/5CS037--Concepts-and-Technologies-of-AI./blob/main/Worksheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4 TO-DO-Task

 Please complete all the problem listed below.

 4.1 Warming Up Exercise:

 Basic Vector and Matrix Operation with Numpy.

 Problem- 1: Array Creation:

 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.
 2. Initialize an all one array with size 4X2.
 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}
 3. Create a 3X3 identity matrix.{Hint:np.eye()}
 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}
 5. Create a 10X10 array with random values and find the minimum and maximum values.
 6. Create a zero array of size 10 and replace 5th element with 1.
 7. Reverse an array arr = [1,2,0,0,4,0].
 8. Create a 2d array with 1 on border and 0 inside.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern.


 Problem- 3: Array Operations:

 For the following arrays:

 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

 v = np.array([9,10]) and w = np.array([11,12]);

 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

 Problem- 4: Matrix Operations:

 • For the following arrays:

 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

 Prove following with Numpy:
 1. Prove A.A−1 = I.
 2. Prove AB̸ = BA.
 3. Prove (AB)T = BTAT.

 • Solve the following system of Linear equation using Inverse Methods.

 2x −3y+z =−1

 x −y+2z =−3

 3x +y−z =9

 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [2]:
# Problem- 1: Array Creation:

import numpy as np

# 1. Initialize an empty array with size 2X2.

two_by_two_arr=np.empty((2,2))
print("Empty two by two array:\n",two_by_two_arr)

Empty two by two array:
 [[1.30304791e-315 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]


In [ ]:
# 2. Initialize an all one array with size 4X2.

all_ones_array=np.ones((4,2))
print("Four by two array with all ones:\n",all_ones_array)


Four by two array with all ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

new_array=np.full((3,3),7)
print("Full array:\n",new_array)


Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

new_array_zeros=np.zeros_like(new_array)
print("Full zeros array:\n",new_array_zeros)

Full zeros array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

new_array_ones=np.ones_like(new_array)
print("\nFull ones array:\n",new_array_ones)


Full ones array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#6.For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

new_list=[1,2,3,4]
list_into_array=np.array(new_list)
print("List converted into array:",list_into_array)

List converted into array: [1 2 3 4]


In [ ]:
# Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

#1.Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

ten_to_fortynine_arr=np.arange(10,50)
print("Array with values from 1 to 49:\n",(ten_to_fortynine_arr))

Array with values from 1 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()

zero_to_eight_matrix=np.arange(0,9)
reshaped_zero_to_eight_matrix=zero_to_eight_matrix.reshape(3,3)
print("3X3 matrix with values ranging from 0 to 8:\n",reshaped_zero_to_eight_matrix)

3X3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3.Create a 3X3 identity matrix.{Hint:np.eye()}

three_by_three_id_matrix=np.eye(3)
print("3X3 identity matrix:\n",three_by_three_id_matrix)

3X3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}

random_size_30_arr=np.random.randint(0,100,size=30)
arr_mean=random_size_30_arr.mean()
print(f"Random array of size 30:\n{random_size_30_arr}\nMean of the array: {arr_mean}")

Random array of size 30:
[64 19 88 77 55 59 61  8 42  5 95 20 44 20 70 40  8 48 34 97 66 27 54 42
 20  7  7 56 80 96]
Mean of the array: 46.96666666666667


In [ ]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.

random_10x10_arr = np.random.randint(0,100,size=(10,10))
min_value = random_10x10_arr.min()
max_value = random_10x10_arr.max()
print(f"10X10 array with random values:\n{random_10x10_arr}\nMax value:{max_value}\nMin value:{min_value}")

10X10 array with random values:
[[59 38 88 34 88 79 75 48 38 29]
 [58 56  4 58 25 54 61 74 27 84]
 [ 0 60 55  0 42 45 89 51 99 33]
 [26 51 81 15 78 97 50 23 86 30]
 [ 0  2  3 84 22  6 75 99 98 58]
 [85 44 35 76 70 69 94 81 50 42]
 [35 82 29 70 87 15 59  0 44  9]
 [66 28 76 89 97 23 78 15 29 90]
 [76 75 54 43 89  1 67 80 13 59]
 [12 59 29 27 84 37 94  7 14 93]]
Max value:99
Min value:0


In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.

size_10_zero_arr=np.zeros(10)
print("Zero array of size 10:\n",size_10_zero_arr)
size_10_zero_arr[4]=1
print("New array:\n",size_10_zero_arr)

Zero array of size 10:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
New array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7. Reverse an array arr = [1,2,0,0,4,0].

arr=[1,2,0,0,4,0]
reversed_arr=arr[::-1]
print("Original array: ",arr,"\nReversed array: ",reversed_arr)

Original array:  [1, 2, 0, 0, 4, 0] 
Reversed array:  [0, 4, 0, 0, 2, 1]


In [ ]:
#8. Create a 2d array with 1 on border and 0 inside.

zero_one_arr=np.ones((5,5))
zero_one_arr[1:-1,1:-1]=0
print("Array with 1 on border and 0 inside:\n",zero_one_arr)


Array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.

checkboard_matrix=np.zeros((8,8))
checkboard_matrix[1::2,::2]=1
checkboard_matrix[::2,1::2]=1
print("Matrix with checkerboard pattern:\n",checkboard_matrix)



Matrix with checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# Problem- 3: Array Operations:

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

#1. Add the two array.

sum_1=np.add(x,y)
sum_2=np.add(w,v)
print("x = ",x,"\n y = ",y,"\n v = ",v,"\n w = ",w)
print(f"x + y = {sum_1}\n w + v = {sum_2}")

x =  [[1 2]
 [3 5]] 
 y =  [[5 6]
 [7 8]] 
 v =  [ 9 10] 
 w =  [11 12]
x + y = [[ 6  8]
 [10 13]]
 w + v = [20 22]


In [ ]:
#2. Subtract the two array.

diff_1=np.subtract(x,y)
diff_2=np.subtract(w,v)
print(f"x - y = {diff_1}\n w - v = {diff_2}")

x - y = [[-4 -4]
 [-4 -3]]
 w - v = [2 2]


In [ ]:
#3. Multiply the array with any integers of your choice.

integer=7
pro_1=integer*x
pro_2=integer*y
pro_3=integer*w
pro_4=integer*v
print(f"2x = {pro_1}\n 2y = {pro_2}\n 2w = {pro_3}\n 2v = {pro_4}")

2x = [[ 7 14]
 [21 35]]
 2y = [[35 42]
 [49 56]]
 2w = [77 84]
 2v = [63 70]


In [ ]:
#4.Find the square of each element of the array.

arrays=[("x",x),("y",y),("v",v),("w",w)]

for name,arr in arrays:
  print("Square of each element of array ",name ,":")
  for element in arr.flat:
    print(f"{element} squared is {element**2}.")

Square of each element of array  x :
1 squared is 1.
2 squared is 4.
3 squared is 9.
5 squared is 25.
Square of each element of array  y :
5 squared is 25.
6 squared is 36.
7 squared is 49.
8 squared is 64.
Square of each element of array  v :
9 squared is 81.
10 squared is 100.
Square of each element of array  w :
11 squared is 121.
12 squared is 144.


In [ ]:
#5.Find the dot product between: v(and)w ; x(and)v ; x(and)y.

dot_product_1=np.dot(v,w)
dot_product_2=np.dot(x,v)
dot_product_3=np.dot(x,y)
print(f"v . w = {dot_product_1}\n x . v = {dot_product_2}\n x . y = {dot_product_3}")

v . w = 219
 x . v = [29 77]
 x . y = [[19 22]
 [50 58]]


In [ ]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.

row_stack=np.vstack((x,y))
column_stack=np.hstack((v,w))
print(f"Vertically stacked array: \n{row_stack}\nHorizontally stacked array:\n {column_stack}")

Vertically stacked array: 
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Horizontally stacked array:
 [ 9 10 11 12]


In [ ]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

concatenated_array=np.concatenate((x,v))
print(concatenated_array)

# X is 2x2 array and v is 1x2 array.So they cannot be concatenated.However,they can be vertically stacked as they have the same number of columns.


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#Problem- 4: Matrix Operations:

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#1. Prove A.A−1 = I.

A_inv=np.linalg.inv(A)
dot=np.round(np.dot(A,A_inv))
id_matrix=np.identity(2)

print("A.A−1 = ",np.round(dot,0))
print("Identity matrix = ",id_matrix)
if np.allclose(dot,id_matrix):
  print("A.A−1 = I \n Hence,proved")

A.A−1 =  [[1. 0.]
 [0. 1.]]
Identity matrix =  [[1. 0.]
 [0. 1.]]
A.A−1 = I 
 Hence,proved


In [ ]:
#2. Prove AB̸ = BA.

AB=np.dot(A,B)
BA=np.dot(B,A)
print("AB = ",AB,"\n BA = ",BA)
if np.allclose(AB,BA):
  print("AB = BA.\n Hence proved")
else:
  print("AB =/= BA.\n Hence proved")

AB =  [[23 13]
 [51 29]] 
 BA =  [[36 44]
 [13 16]]
AB =/= BA.
 Hence proved


In [ ]:
#3. Prove (AB)T = BTAT.

AB_T=AB.T
B_T=B.T
A_T=A.T
B_T_A_T=np.dot(B_T,A_T)

print("ABT = ",AB_T)
print("BTAT = ",B_T_A_T)
if (np.allclose(AB_T,B_T_A_T)):
  print("(AB)T = BTAT.\n Hence proved.")

ABT =  [[23 51]
 [13 29]]
BTAT =  [[23 51]
 [13 29]]
(AB)T = BTAT.
 Hence proved.


In [ ]:
# Solve the following system of Linear equation using Inverse Methods.
#  2x −3y+z =−1
#  x −y+2z =−3
#  3x +y−z =9

A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
X=(["x","y","z"])
A_inverse=np.linalg.inv(A)
Solution=np.dot(A_inverse,B)
print("2x −3y+z =−1\nx −y+2z =−3\n3x +y−z =9")
print("Solution:\n")
for var,ans in zip(X,Solution):
  print(var," = ",ans)

2x −3y+z =−1
x −y+2z =−3
3x +y−z =9
Solution:

x  =  2.0
y  =  1.0
z  =  -2.0


4.2 Experiment: How Fast is Numpy?

 In this exercise, you will compare the performance and implementation of operations using plain Python
 lists (arrays) and NumPy arrays. Follow the instructions:

 1. Element-wise Addition:

 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
 and Print the time taken for this operation.

 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
 operation.

 2. Element-wise Multiplication

 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Mea
sure and Print the time taken for this operation.

 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
 operation.

 3. Dot Product

 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
 Print the time taken for this operation.

 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
 operation.

 4. Matrix Multiplication

 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
 and print the time taken for this operation.

 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.

In [10]:
#1. Element-wise Addition:

import numpy as np
import time

list_1=list(range(1000000))
list_2=list(range(1000000))
sum_1=[]
start_time=time.time()
for a,b in zip(list_1,list_2):
        sum_1.append(a+b)
end_time=time.time()
time_taken=end_time-start_time
print("Time taken to perform element-wise addition using python lists:",time_taken,"seconds.")

arr_1=np.arange(1000000)
arr_2=np.arange(1000000)

start_time=time.time()
sum_2=arr_1+arr_2
end_time=time.time()
time_taken=end_time-start_time
print("Time taken to perform element-wise addition using numpy array:",time_taken,"seconds.")


Time taken to perform element-wise addition using python lists: 0.13928651809692383 seconds.
Time taken to perform element-wise addition using numpy array: 0.0022220611572265625 seconds.


In [11]:
#Element wise Multiplication

list_1=list(range(1000000))
list_2=list(range(1000000))
product_1=[]
start_time=time.time()
for a,b in zip(list_1,list_2):
        product_1.append(a*b)
end_time=time.time()
time_taken=end_time-start_time
print("Time taken to perform element-wise multiplication using python lists:",time_taken,"seconds.")

arr_1=np.arange(1000000)
arr_2=np.arange(1000000)

start_time=time.time()
pro_2=arr_1*arr_2
end_time=time.time()
time_taken=end_time-start_time
print("Time taken to perform element-wise multiplication using numpy array:",time_taken,"seconds.")


Time taken to perform element-wise multiplication using python lists: 0.23310112953186035 seconds.
Time taken to perform element-wise multiplication using numpy array: 0.0022840499877929688 seconds.


In [12]:
#3. Dot Product

list_1=list(range(1000000))
list_2=list(range(1000000))
start_time=time.time()
product_1=[]
for a,b in zip(list_1,list_2):
        product_1.append(a*b)

dot_product_1=sum(product_1)
end_time=time.time()
time_taken=end_time-start_time
print("Time taken to compute dot product using python lists:",time_taken,"seconds.")

arr_1=np.arange(1000000)
arr_2=np.arange(1000000)

start_time=time.time()
dot_pro_2=np.dot(arr_1,arr_2)
end_time=time.time()
time_taken=end_time-start_time
print("Time taken to compute dot product using numpy array:",time_taken,"seconds.")


Time taken to compute dot product using python lists: 0.3296196460723877 seconds.
Time taken to compute dot product using numpy array: 0.002167224884033203 seconds.


In [13]:
#4. Matrix Multiplication

arr_1=np.ones((1000,1000),dtype=int)
arr_2=np.ones((1000,1000),dtype=int)

start_time=time.time()
Matrix_product_1=np.matmul(arr_1,arr_2)
end_time=time.time()
time_taken=end_time-start_time
print("Time taken to perform matrix multiplication using numpy array:",time_taken,"seconds.")


list_1=arr_1.tolist()
list_2=arr_2.tolist()
Matrix_product_2=np.zeros((1000,1000),dtype=int).tolist()

start_time=time.time()
for i in range(len(list_1)):
  for j in range(len(list_2[0])):
    total=0
    for k in range (len(list_2)):
      total+=list_1[i][k]*list_2[k][j]
    Matrix_product_2[i][j]=total

end_time=time.time()
time_taken=end_time-start_time
print("Time taken to perform matrix multiplication using python lists:",time_taken,"seconds.")

Time taken to perform matrix multiplication using numpy array: 2.8702030181884766 seconds.
Time taken to perform matrix multiplication using python lists: 228.68940210342407 seconds.
